//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parser
{
    using System;
    using System.Collections.Generic;
    
    public partial class adddb
    {
        public int Id { get; set; }
        public string header { get; set; }
        public string col { get; set; }
    }
}
