//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cinemcass
{
    using System;
    using System.Collections.Generic;
    
    public partial class cinema
    {
        internal readonly cinema Local;

        public int Idcinema { get; set; }
        public string header { get; set; }
        public string col { get; set; }
    }
}
